name: Deploy Fib Calculator

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run front-end tests
      run: |
        echo "Build a docker image for tests"
        docker build -t frontend-test -f ./client/Dockerfile.dev ./client
        echo "Run tests against that image"
        docker run -e CI=true frontend-test npm test
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ca-central-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push the front-end image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: docker_multi_container_deployment_frontend
        IMAGE_TAG: ${{ github.sha }}
      run: |
        echo "Build the front-end production docker image"
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./client
        echo "Pushing the image to ECR..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"