name: Destroy Application On Demand

on:
  workflow_dispatch:

env:
  AWS_REGION: ca-central-1
  PROJECT_NAME: docker_multi_container_deployment
  BEANSTALK_ENVIRONMENT: Dockermulticontainerdeployment-staging

jobs:
  destroy:
    name: Destroy
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Destroy Staging Environment
      run: |
        terraform -chdir=./ci/deploy/staging init -backend-config=../backend-staging.tf
        terraform -chdir=./ci/deploy/staging destroy --auto-approve -var 'project='"${{ env.PROJECT_NAME }}"'' -var 'postgres_password='"${{ secrets.POSTGRES_PASSWORD }}"'' -var 'beanstalk_environment='"${{ env.BEANSTALK_ENVIRONMENT }}"''

    - name: Destroy Common Resources
      run: |
        terraform -chdir=./ci/prebuild init
        terraform -chdir=./ci/prebuild destroy --auto-approve -var 'project='"${{ env.PROJECT_NAME }}"'' -var 'project_modules=["client", "nginx", "server", "worker"]'
